### ISSUE TITLE
Please update the repository

### ISSUE THREAD

**Issue by AsesinoBlade** [kksvt/obrandomizer#1]
Hi kksvt,
First of all, thank you for creating this (it is very fun) and for providing the source code so we can all tweak it to our heart’s content,.  :).  I was wondering, if you wouldn’t mind updating your repository to the latest version.   This version of the code appears to be out of date.   I noticed that the container randomization enable feature does not appear in the source. (unless I am misreading things)
I want to make sure that I have the latest before I make any code tweaks for my personal use.

thanks kksvt,
a

**Comment by kksvt** [comment]
Hey a,
you're welcome and thank you for your kind words! The repository is indeed slightly out of date compared to my local version, since I started working on a spell randomization all the way back in August along with some tweaks and I never really finished it (with hindsight I should've just made a separate branch, but I pretty much expected to be done with it just a couple of weeks later and now it's somehow February lol). I'll try to clean up the code and create a separate dev branch or just wrap up the new features and make a release tomorrow at the latest (probably the former though).
Having said that, the container randomization option is a part of the ESP file - it's a bad practice that a lot of the features are split between the OBSE plugin and the ESP scripts, but unfortunately that's how it is for now. The option itself is checked inside the *ZZZOBRNRandInv* script, line 64 (though the ESP file in this repo is currently outdated compared to the *Container Randomization Disable for 1.0.1* on Nexus). Hope that helps!

**Comment by AsesinoBlade** [comment]
Ah, i didn’t even think to look inside the ESP; that makes a lot of sense.   Wow, spell randomization sounds awesome, I can’t wait to see that in action.

Thank you again for all you’ve done!
a
